pms/pms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pms/project/urls.py
from django.urls import path

from . import views


app_name = 'project'


urlpatterns = [
    path('', views.projects, name='projects'),
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.project, name='project'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
    path('<uuid:project_id>/files/upload/', views.upload_file, name='upload_file'),
    path('<uuid:project_id>/files/<uuid:pk>/delete/', views.delete_file, name='delete_file'),
    path('<uuid:project_id>/notes/add/', views.add_note, name='add_note'),
    path('<uuid:project_id>/notes/<uuid:pk>/', views.note_detail, name='note_detail'),
    path('<uuid:project_id>/notes/<uuid:pk>/edit/', views.note_edit, name='note_edit'),
    path('<uuid:project_id>/notes/<uuid:pk>/delete/', views.note_delete, name='note_delete'),
]

pms/task/urls.py
from django.urls import path

from . import views


app_name = 'task'


urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.detail, name='detail'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
]

pms/todolist/urls.py
from django.urls import path

from . import views


app_name = 'todolist'


urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.todolist, name='todolist'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
]

pms/todolist/models.py
import uuid

from django.db import models

from account.models import User
from project.models import Project


class Todolist(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, related_name='todolists', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='todolists', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

pms/todolist/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .models import Todolist
from project.models import Project


@login_required
def todolist(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=pk)

    return render(request, 'todolist/todolist.html', {
        'project': project,
        'todolist': todolist
    })


@login_required
def add(request, project_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            Todolist.objects.create(project=project, name=name, description=description, created_by=request.user)

            return redirect(f'/projects/{project_id}')

    return render(request, 'todolist/add.html', {
        'project': project
    })


@login_required
def edit(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=pk)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            todolist.name = name
            todolist.description = description
            todolist.save()

            return redirect(f'/projects/{project_id}/{pk}/')

    return render(request, 'todolist/edit.html', {
        'project': project,
        'todolist': todolist
    })


@login_required
def delete(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=pk)
    todolist.delete()

    return redirect(f'/projects/{project_id}/')

pms/todolist/templates/todolist/add.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Add to-do-list</h1>

    <form class="mt-6 px-8 space-y-4" method="post" action=".">
      {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input name="name" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label>Description</label><br>
            <textarea name="description" class="w-full py-4 px-6 bg-slate-500 text-white"></textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
        </div>
    </form>

{% endblock %}

pms/todolist/templates/todolist/edit.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Edit to-do-list</h1>

    <form class="mt-6 px-8 space-y-4" method="post" action=".">
      {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input name="name" value="{{ todolist.name }}" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label>Description</label><br>
            <textarea name="description" class="w-full py-4 px-6 bg-slate-500 text-white">{{ todolist.description }}</textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
        </div>
    </form>

{% endblock %}

pms/todolist/templates/todolist/todolist.html
{% extends 'core/base.html' %}

{% block content %}

    <a href="{% url 'project:project' project.id %}">
        <div class="flex mb-6 gap-x-1">
            <svg class="self-center w-6 h-6 dark:text-slate" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 8 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 1 1.3 6.326a.91.91 0 0 0 0 1.348L7 13"/>
            </svg>
            <p class="self-center text-6">back</p>
        </div>
    </a>

    <h1 class="mb-6 text-3xl">{{ todolist.name }}</h1>

    {% if todolist.description %}
        <p class="mb-6">{{ todolist.description }}</p>
    {% endif %}

    <a href="{% url 'task:add' project.id todolist.id %}" class="py-4 px-8 bg-sky-600 text-white inline-block">Add task</a>
    <a href="{% url 'todolist:edit' project.id todolist.id %}" class="py-4 px-8 bg-sky-600 text-white inline-block">Edit</a>
    <a href="{% url 'todolist:delete' project.id todolist.id %}" class="py-4 px-8 bg-amber-600 text-white inline-block">Delete</a>

    <div class="mt-6 grid grid-cols-4 gap-4">

        {% for task in todolist.tasks.all %}

            {% if task.is_done %}
            <div class="flex gap-2 py-6 px-6 bg-slate-400 text-slate-800">
                <a href="{% url 'task:detail' todolist.project.id todolist.id task.id %}?is_done=no"><h2 class="text-xl">🗹</h2></a>
                <a href="{% url 'task:detail' todolist.project.id todolist.id task.id %}">
                    <h2 class="mb-4 text-xl"><s>{{ task.name }}</s></h2>

                    <p class="text-sm"><s>{{ task.description }}</s></p>
                </a>
            </div>

            {% else %}
            <div class="flex gap-2 py-6 px-6 bg-slate-100 text-slate-700">
                <a href="{% url 'task:detail' todolist.project.id todolist.id task.id %}?is_done=yes"><h2 class="text-xl">☐</h2></a>
                <a href="{% url 'task:detail' todolist.project.id todolist.id task.id %}">
                    <h2 class="mb-4 text-xl">{{ task.name }}</h2>

                    <p class="text-sm">{{ task.description }}</p>
                </a>
            </div>
            {% endif %}

        {% endfor %}

    </div>
{% endblock %}