pms/pms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pms/task/urls.py
from django.urls import path

from . import views


app_name = 'task'


urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.detail, name='detail'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
]

pms/todolist/urls.py
from django.urls import path

from . import views


app_name = 'todolist'


urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.todolist, name='todolist'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
]

pms/task/models.py
import uuid

from django.db import models

from account.models import User
from project.models import Project
from todolist.models import Todolist


class Task(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, related_name='tasks', on_delete=models.CASCADE)
    todolist = models.ForeignKey(Todolist, related_name='tasks', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='tasks', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

pms/task/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from project.models import Project
from todolist.models import Todolist
from .models import Task

from urllib.parse import urlparse


@login_required
def add(request, project_id, todolist_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        Task.objects.create(project=project,todolist=todolist, name=name, description=description, created_by=request.user)

        return redirect(f'/projects/{project_id}/{todolist_id}/')

    return render(request, 'task/add.html')


@login_required
def detail(request, project_id, todolist_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=pk)

    if request.GET.get('is_done', '') == 'yes':
        task.is_done = True
        task.save()
    if request.GET.get('is_done', '') == 'no':
        task.is_done = False
        task.save()

    if request.GET.get('is_done', '') in ('yes', 'no') and (
            urlparse(request.META.get('HTTP_REFERER')).path == f'/projects/{project_id}/{todolist_id}/'
    ):
        return redirect(f'/projects/{project_id}/{todolist_id}/')

    return render(request, 'task/detail.html', {
        'project': project,
        'todolist': todolist,
        'task': task
    })


@login_required
def edit(request, project_id, todolist_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=pk)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            task.name = name

            task.description = description
            task.save()

            return redirect(f'/projects/{project_id}/{todolist_id}/{pk}/')

    return render(request, 'task/edit.html', {
        'task': task
    })


@login_required
def delete(request, project_id, todolist_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=pk)
    task.delete()

    return redirect(f'/projects/{project_id}/{todolist_id}/')

pms/task/templates/task/add.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Add task</h1>

    <form class="mt-6 px-8 space-y-4" method="post" action=".">
      {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input name="name" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label>Description</label><br>
            <textarea name="description" class="w-full py-4 px-6 bg-slate-500 text-white"></textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
        </div>
    </form>

{% endblock %}

pms/task/templates/task/detail.html
{% extends 'core/base.html' %}

{% block content %}

    <a href="{% url 'todolist:todolist' project.id todolist.id %}">
        <div class="flex mb-6 gap-x-1">
            <svg class="self-center w-6 h-6 dark:text-slate" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 8 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 1 1.3 6.326a.91.91 0 0 0 0 1.348L7 13"/>
            </svg>
            <p class="self-center text-6">back</p>
        </div>
    </a>

    <h1 class="mb-6 text-3xl">{{ task.name }}</h1>

    <p class="mb-6"><strong class="font-bold">Status:</strong> {% if task.is_done %}🗹 done{% else %}☐ to-do{% endif %}</p>

    {% if task.description %}
        <p class="mb-6">{{ task.description }}</p>
    {% endif %}

    {% if not task.is_done %}
        <a href="?is_done=yes" class="py-4 px-8 bg-emerald-600 text-white inline-block">Mark as 🗹 done</a>
    {% else %}
        <a href="?is_done=no" class="py-4 px-8 bg-gray-600 text-white inline-block">Switch to ☐ to-do</a>
    {% endif %}
    <a href="{% url 'task:edit' task.project_id task.todolist_id task.id %}" class="py-4 px-8 bg-sky-600 text-white inline-block">Edit</a>
    <a href="{% url 'task:delete' task.project_id task.todolist_id task.id %}" class="py-4 px-8 bg-amber-600 text-white inline-block">Delete</a>

{% endblock %}

pms/task/templates/task/edit.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Edit task</h1>

    <form class="mt-6 px-8 space-y-4" method="post" action=".">
      {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input value="{{ task.name }}" name="name" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label>Description</label><br>
            <textarea name="description" class="w-full py-4 px-6 bg-slate-500 text-white">{{ task.description }}</textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Save changes</button>
        </div>
    </form>

{% endblock %}